# Use the default shell
SHELL := /bin/bash

# Define common variables
PYTHON3 = python3
PYTHON = ../venv/Scripts/python
PIP = ./venv/Scripts/pip

calibrate:
	$(PYTHON) core/calibration/hand_calibartion.py

run-home:
	$(PYTHON) home_screen.py

run-home-original:
	$(PYTHON) home_screen_original.py

run:
	$(PYTHON) main.py

run3:
    $(PYTHON3) main.py

run-text:

# pip install RealtimeSTT --index-url https://pypi.org/simple